[theme]
primaryColor = "#1E3A8A"
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 200
enableCORS = false

[browser]
gatherUsageStats = false
